package {{packageName}}.infrastructure

import io.ktor.client.call.receive
import io.ktor.client.features.ResponseException

{{#nonPublicApi}}internal {{/nonPublicApi}}class ErrorWrapper(
    val originalException: ResponseException,
    val error: Any?
) : Exception()

internal suspend inline fun <reified E: Any>ResponseException.toErrorWrapper(): ErrorWrapper {
    val error = try {
        response.receive<E>()
    } catch (ignored: Throwable) {
        null
    }
    return ErrorWrapper(originalException = this, error = error)
}